# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3738daee4963e752463f6f5dc797646c9edb5dba14362ae4d676db82477de1a1fd1e19ad05dbfb797370392adba62512ed2c27d59557ec471dd09a0b5350888f

test:
  secret_key_base: 6a8a19bf6b05e0965197fab2b11e5dac0b1c5ad743fc9fa89912686a0fc264c20031970bf0c23943f7b7a2817176d287c83acfd8611fbb825722eb38f827c7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
